apiVersion: v1 # 사용할 Kubernetes API 버전
kind: PersistentVolumeClaim # 리소스의 종류: PersistentVolumeClaim
metadata: # 리소스의 메타데이터 설정
  name: db-pvc # PersistentVolumeClaim의 이름
spec: # 세부 설정
  accessModes: # 액세스 모드 설정
    - ReadWriteOnce # 읽기/쓰기 액세스 모드 설정
  resources: # 리소스 요청 설정
    requests: # 요청한 리소스 설정
      storage: 5G # 저장소 용량 요청 설정
